name: PairingNet
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.13
  - numpy=1.21.5
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - matplotlib=3.5.3
  - seaborn=0.12.1
  - pytorch=1.12.1=py3.7_cuda11.3_cudnn8.3.2_0
  - torchvision=0.13.1=py37_cu113
  - torchaudio=0.12.1=py37_cu113
  - cudatoolkit=11.3.1
  - tensorflow=2.2.0
  - tensorflow-estimator=2.6.0
  - tensorboard=2.9.0
  - keras=2.3.1
  - h5py=2.10.0
  - pillow=9.4.0
  - tqdm=4.64.1
  - protobuf=3.20.1
  - yaml=0.2.5
  - requests=2.28.1
  - pip
  - pip:
    - einops==0.6.1
    - timm==0.6.11
    - torch-geometric==2.3.0
    - tensorboardx==2.6
    - plotly==5.13.1
    - shapely==2.0.1
    - open3d==0.17.0
    - pyquaternion==0.9.9
    - tf-keras-vis==0.8.2
    - opencv-python==4.6.0.66
    - hausdorff
    - numba
    - pytorch_warmup
    - torchsummary
